"""Sync machine-verifiable facts into README.md generated regions.

terraform-docs marker pattern: scripts own facts, humans own the prose
around them. Only the region between the BEGIN/END markers is rewritten.

    <!-- BEGIN GENERATED: repo-facts -->
    ...regenerated content...
    <!-- END GENERATED: repo-facts -->

Run:  uv run python scripts/readme_sync.py build   # rewrite the region
      uv run python scripts/readme_sync.py check   # exit 1 if stale (CI)

Tests are keyless (all external libs mocked), so the count is collected
without any submodule or network.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
README = ROOT / "README.md"
PKG = ROOT / "src" / "airllm_benchmark"
BEGIN = "<!-- BEGIN GENERATED: repo-facts -->"
END = "<!-- END GENERATED: repo-facts -->"


def _collect(cmd: list[str]) -> subprocess.CompletedProcess[str] | None:
    try:
        return subprocess.run(
            cmd, capture_output=True, text=True, cwd=ROOT, timeout=180,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None


def _test_count() -> str:
    """Count collected tests; degrade honestly if pytest is unavailable.

    Prefer the uv-managed environment (PRD: uv-only); fall back to a plain
    pytest on PATH when uv is absent or cannot resolve the env.
    """
    base = ["--collect-only", "-q"]
    out: subprocess.CompletedProcess[str] | None = None
    for cmd in (["uv", "run", "pytest", *base], ["pytest", *base]):
        result = _collect(cmd)
        if result is not None and result.returncode == 0:
            out = result
            break
    if out is None:
        return "n/a (pytest unavailable)"
    match = re.search(r"(\d+)\s+tests?\s+(?:collected|selected)", out.stdout)
    return f"{match.group(1)} collected" if match else "n/a"


def _module_table() -> str:
    """Line-count inventory of src modules (150-line rule evidence)."""
    rows = ["| Module | Lines |", "|--------|-------|"]
    for p in sorted(PKG.rglob("*.py")):
        if "__pycache__" in p.parts:
            continue
        n = len(p.read_text(encoding="utf-8").splitlines())
        rows.append(f"| `{p.relative_to(ROOT / 'src')}` | {n} |")
    return "\n".join(rows)


def _hardware_facts() -> str:
    """Summarize the documented benchmark hardware."""
    path = ROOT / "config" / "hardware.json"
    if not path.exists():
        return "- `config/hardware.json`: MISSING"
    hw = json.loads(path.read_text(encoding="utf-8"))
    note = "  ⚠ placeholder — document real specs before benchmarking" \
        if "placeholder" in path.read_text(encoding="utf-8").lower() else ""
    return (
        f"- CPU: {hw.get('cpu', '?')}\n"
        f"- GPU: {hw.get('gpu', '?')}\n"
        f"- RAM: {hw.get('ram_gb', '?')} GB / Disk free: "
        f"{hw.get('disk_free_gb', '?')} GB\n"
        f"- OS: {hw.get('os', '?')}{note}"
    )


def _render() -> str:
    return (
        f"{BEGIN}\n"
        f"_Facts below are generated by `scripts/readme_sync.py` — do not edit._\n\n"
        f"**Tests:** {_test_count()}\n\n"
        f"**Modules (150-line rule):**\n\n{_module_table()}\n\n"
        f"**Benchmark hardware:**\n{_hardware_facts()}\n"
        f"{END}"
    )


def _inject(text: str, block: str) -> str:
    start = text.find(BEGIN)
    end = text.find(END)
    if start == -1 or end == -1:
        raise SystemExit(
            f"README.md is missing the markers:\n  {BEGIN}\n  {END}\n"
            "Add them once where the facts block should live."
        )
    return text[:start] + block + text[end + len(END):]


def main() -> int:
    """Build or check the generated repo-facts region in README.md."""
    mode = sys.argv[1] if len(sys.argv) > 1 else "build"
    current = README.read_text(encoding="utf-8")
    updated = _inject(current, _render())
    if mode == "check":
        if current != updated:
            print("STALE: README repo-facts region is out of date. "
                  "Run: uv run python scripts/readme_sync.py build")
            return 1
        print("OK: README repo-facts region is up to date")
        return 0
    README.write_text(updated, encoding="utf-8")
    print("README repo-facts region rewritten")
    return 0


if __name__ == "__main__":
    sys.exit(main())
